### ISSUE TITLE
Melhoria da Navegação - Menu Nav em todas as páginas

### ISSUE THREAD

**Issue by Pancosta** [LukeVanHagen/Projeto2IF#15]
Como um usuário do sistema, gostaria de ter acesso ao menu de navegação "Welcome" em todas as páginas, para facilitar a minha experiência de uso e melhorar a usabilidade do sistema.

Como parte da melhoria contínua do sistema, identificamos a necessidade de aprimorar a navegação do usuário. Atualmente, o menu de navegação "Welcome" está disponível apenas na página inicial do sistema, o que dificulta a movimentação entre as diferentes seções e funcionalidades. Para melhorar essa situação, decidimos implementar o menu de navegação "Welcome" em todas as páginas.

Critérios de aceitação:

O menu de navegação "Welcome" deve ser visível em todas as páginas do sistema.
O menu deve conter os links relevantes para as seções e funcionalidades do sistema.
Ao clicar em um link no menu, o usuário deve ser direcionado corretamente para a página correspondente.
A implementação do menu de navegação "Welcome" deve seguir as diretrizes de design estabelecidas pela equipe de UX/UI.

Tarefa a ser realizada:

- [x] Adicionar o menu de navegação "Welcome" em todas as páginas do sistema.
- [x] Verificar e ajustar a lógica de redirecionamento para garantir que os links funcionem corretamente.

**Comment by LukeVanHagen** [comment]
Feito
