### ISSUE TITLE
Criar sistema de marcação de consultas

### ISSUE THREAD

**Issue by Pancosta** [LukeVanHagen/Projeto2IF#6]
COMO paciente do PsicoMais QUERO um serviço de agendamento  PARA marcação de consultas

Critério de aceitação :

- [x] Formulário de disponibilidade do profissional
- [x] Formulário dinâmico para marcação de consultas do paciente
- [x] Em caso de não haver data disponível deve-se informar ao cliente
- [x] Lista de consultas agendadas para visualização e cancelamento
- [x] Limite de uma consulta por semana para o paciente

**Comment by LukeVanHagen** [comment]
Marcação de consulta funcional !
